trigger:
- main  # Adjust according to your branch

variables:
  azureSubscription: 'Ramesh_test_acr'  # Name of the Azure service connection
  azureContainerRegistry: 'testcon'  # Name of your Azure Container Registry
  imageName: 'my-node-app'
  dockerfilePath: 'Dockerfile'
  buildContext: '.'

jobs:
- job: BuildAndPush
  displayName: Build and Push Docker Image
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      containerRegistry: $(azureSubscription)
      repository: $(azureContainerRegistry)/$(imageName)
      dockerfile: $(dockerfilePath)
      buildContext: $(buildContext)
      tags: 'latest'
